### ISSUE TITLE
Can't find / install module 'clients.people'

### ISSUE THREAD

**Issue by williamblair333** [automationhacks/course-api-framework-python#8]
OS: Windows 10 x64 21H2 19044.1466
Python: 3.9

OS: Debian 11
Python: 3.9

I run python3 -m people_test.py and get error ModuleNotFoundError: No module named 'clients.people'

I run python3 -m pip install clients.people receive error ERROR: No matching distribution found for clients.people
```
(people-api-wwEwet5F) C:\projects\TAU\api\course-api-framework-python\tests>python3 -m people_test.py
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\projects\TAU\api\course-api-framework-python\tests\people_test.py", line 3, in <module>
    from clients.people.people_client import PeopleClient
ModuleNotFoundError: No module named 'clients.people'

(people-api-wwEwet5F) C:\projects\TAU\api\course-api-framework-python\tests>python3 -m pip install clients.people
ERROR: Could not find a version that satisfies the requirement clients.people (from versions: none)
ERROR: No matching distribution found for clients.people

```

**Comment by automationhacks** [comment]
Hi @williamblair333, You don't need to install the module. If you follow the tutorial, you'll need to run `build_database.py` from `people-api` project and then`python server.py`, post that when you run the tests it should work. Also check if pipenv is active from the command line you are running from. You can activate pipenv by running `pipenv shell`.

If this does not work, please give detailed steps on what you are trying and the state of the services. Feel free to reopen this issue in case you need further help.
